package Model;
// Generated 25/10/2020 08:43:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer idEmpleado;
     private String nombre;
     private String APaterno;
     private String AMaterno;
     private Long telefono;
     private String direccion;
     private String correo;
     private String puesto;
     private Date horaEntrada;
     private Date horaSalida;
     private Double salarioQuincenal;
     private Set ventases = new HashSet(0);

    public Empleados() {
    }

    public Empleados(String nombre, String APaterno, String AMaterno, Long telefono, String direccion, String correo, String puesto, Date horaEntrada, Date horaSalida, Double salarioQuincenal, Set ventases) {
       this.nombre = nombre;
       this.APaterno = APaterno;
       this.AMaterno = AMaterno;
       this.telefono = telefono;
       this.direccion = direccion;
       this.correo = correo;
       this.puesto = puesto;
       this.horaEntrada = horaEntrada;
       this.horaSalida = horaSalida;
       this.salarioQuincenal = salarioQuincenal;
       this.ventases = ventases;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAPaterno() {
        return this.APaterno;
    }
    
    public void setAPaterno(String APaterno) {
        this.APaterno = APaterno;
    }
    public String getAMaterno() {
        return this.AMaterno;
    }
    
    public void setAMaterno(String AMaterno) {
        this.AMaterno = AMaterno;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public Date getHoraEntrada() {
        return this.horaEntrada;
    }
    
    public void setHoraEntrada(Date horaEntrada) {
        this.horaEntrada = horaEntrada;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }
    public Double getSalarioQuincenal() {
        return this.salarioQuincenal;
    }
    
    public void setSalarioQuincenal(Double salarioQuincenal) {
        this.salarioQuincenal = salarioQuincenal;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }




}


