package Model;
// Generated 25/10/2020 08:43:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private String descripcion;
     private Integer cantidadStock;
     private Date abastecido;
     private Double precioMenudeo;
     private Double precioMayoreo;
     private Set<VentaProducto> ventaproductos = new HashSet<VentaProducto>(0);
    public Productos() {
    }

    public Productos(String descripcion, Integer cantidadStock, Date abastecido, Double precioMenudeo, Double precioMayoreo, Set ventaproductos) {
       this.descripcion = descripcion;
       this.cantidadStock = cantidadStock;
       this.abastecido = abastecido;
       this.precioMenudeo = precioMenudeo;
       this.precioMayoreo = precioMayoreo;
       this.ventaproductos = ventaproductos;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getCantidadStock() {
        return this.cantidadStock;
    }
    
    public void setCantidadStock(Integer cantidadStock) {
        this.cantidadStock = cantidadStock;
    }
    public Date getAbastecido() {
        return this.abastecido;
    }
    
    public void setAbastecido(Date abastecido) {
        this.abastecido = abastecido;
    }
    public Double getPrecioMenudeo() {
        return this.precioMenudeo;
    }
    
    public void setPrecioMenudeo(Double precioMenudeo) {
        this.precioMenudeo = precioMenudeo;
    }
    public Double getPrecioMayoreo() {
        return this.precioMayoreo;
    }
    
    public void setPrecioMayoreo(Double precioMayoreo) {
        this.precioMayoreo = precioMayoreo;
    }
    public Set<VentaProducto> getVentaproductos() {
        return this.ventaproductos;
    }
    
    public void setVentaproductos(Set<VentaProducto> ventaproductos) {
        this.ventaproductos = ventaproductos;
    }




}


