package Model;
// Generated 25/10/2020 08:43:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private Integer idVenta;
     private Clientes clientes;
     private Empleados empleados;
     private VentaProducto ventaproducto;
     private Integer cantidadVenta;
     private Date fechaVenta;
     private Date fechaRegistro;
     private Double montoTransporte;
     private Double iva;
     private Double precioFinal;

    public Ventas() {
    }

    public Ventas(Clientes clientes, Empleados empleados,VentaProducto ventaproducto, Integer cantidadVenta, Date fechaVenta, Date fechaRegistro, Double montoTransporte, Double iva, Double precioFinal) {
       this.clientes = clientes;
       this.empleados = empleados;
       this.ventaproducto = ventaproducto;
       this.cantidadVenta = cantidadVenta;
       this.fechaVenta = fechaVenta;
       this.fechaRegistro = fechaRegistro;
       this.montoTransporte = montoTransporte;
       this.iva = iva;
       this.precioFinal = precioFinal;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public VentaProducto getVentaproducto() {
        return this.ventaproducto;
    }
    
    public void setVentaproducto(VentaProducto ventaproducto) {
        this.ventaproducto = ventaproducto;
    }
    public Integer getCantidadVenta() {
        return this.cantidadVenta;
    }
    
    public void setCantidadVenta(Integer cantidadVenta) {
        this.cantidadVenta = cantidadVenta;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Double getMontoTransporte() {
        return this.montoTransporte;
    }
    
    public void setMontoTransporte(Double montoTransporte) {
        this.montoTransporte = montoTransporte;
    }
    public Double getIva() {
        return this.iva;
    }
    
    public void setIva(Double iva) {
        this.iva = iva;
    }
    public Double getPrecioFinal() {
        return this.precioFinal;
    }
    
    public void setPrecioFinal(Double precioFinal) {
        this.precioFinal = precioFinal;
    }




}


